version: "3"

services:
  fluentd:
    container_name: "fluentd"
    build: .
    volumes:
      - ./config:/fluentd/etc
    ports:
      - "24224:24224"
      - "24224:24224/udp"

networks:
  default:
    external: true
    name: micro-microservice-network
